---
# Audited: Remapping completed
- name: "5.3.1 | PATCH | Ensure sudo is installed"
  apt:
      name: "{{ ubtu22cis_sudo_package }}"
      state: present
  when:
      - ubtu22cis_rule_5_3_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.1
      - sudo

- name: "5.3.2 | PATCH | Ensure sudo commands use pty"
  lineinfile:
      path: /etc/sudoers
      regexp: '^Defaults        use_'
      line: 'Defaults        use_pty'
      insertafter: '^Defaults'
  when:
      - ubtu22cis_rule_5_3_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.2
      - sudo

- name: "5.3.3 | PATCH | Ensure sudo log file exists"
  lineinfile:
      path: /etc/sudoers
      regexp: '^Defaults        logfile'
      line: 'Defaults        logfile="{{ ubtu22cis_sudo_logfile }}"'
      insertafter: '^Defaults'
  when:
      - ubtu22cis_rule_5_3_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.3
      - sudo

# (Level 2 - Server) 5.3.4 Ensure users must provide password for privilege escalation

# Need 5.3.5 Ensure re-authentication for privilege escalation is not disabled globally

# Need 5.3.6 Ensure sudo authentication timeout is configured correctly

- name: "5.3.7 | PATCH | Ensure access to the su command is restricted"
  block:
      - name: "5.3.7 | PATCH | Ensure access to the su command is restricted | Check for pam_wheel.so module"
        command: grep '^auth.*required.*pam_wheel' /etc/pam.d/su
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu22cis_5_3_7_pam_wheel_status

      - name: "5.7 | PATCH | Ensure access to the su command is restricted | Create empty sugroup"
        group:
            name: "{{ ubtu22cis_su_group }}"

      - name: "5.7 | PATCH | Ensure access to the su command is restricted | Set pam_wheel if exists"
        pamd:
            name: su
            type: auth
            control: required
            module_path: pam_wheel.so
            module_arguments: 'use_uid group={{ ubtu22cis_su_group }}'
        when: ubtu22cis_5_3_7_pam_wheel_status.stdout | length > 0

      - name: "5.7 | PATCH | Ensure access to the su command is restricted | Set pam_wheel if does not exist"
        lineinfile:
            path: /etc/pam.d/su
            line: 'auth       required   pam_wheel.so use_uid group={{ ubtu22cis_su_group }}'
            create: yes
        when: ubtu22cis_5_3_7_pam_wheel_status.stdout | length == 0
  when:
      - ubtu22cis_rule_5_3_7
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.3.7
      - user
