---

- name: "4.2.3 | PATCH | Ensure all logfiles have appropriate permissions and ownership"
  block:
      - name: "4.2.3 | PATCH | Ensure all logfiles have appropriate permissions and ownership | Find log files"
        find:
            paths: /var/log
            recurse: yes
        register: ubtu22cis_4_2_3_logfiles

      - name: "4.2.3 | PATCH | Ensure all logfiles have appropriate permissions and ownership | Apply permissions and ownership"
        file:
            path: "{{ item.path }}"
            mode: 0640
        with_items:
            - "{{ ubtu22cis_4_2_3_logfiles.files }}"
        loop_control:
            label: "{{ item.path }}"
  when:
      - ubtu22cis_rule_4_2_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_4.2.3
      - logfiles
      - permissions
