---

# Need 4.2.1.1.1 Ensure systemd-journal-remote is installed

# Need 4.2.1.1.2 Ensure systemd-journal-remote is configured

# Need 4.2.1.1.3 Ensure systemd-journal-remote is enabled

# Need 4.2.1.1.4 Ensure journald is not configured to recieve logs from a remote client

# Need 4.2.1.2 Ensure journald service is enabled

- name: "4.2.1.3 | PATCH | Ensure journald is configured to compress large log files"
  lineinfile:
      path: /etc/systemd/journald.conf
      regexp: '^Compress|^#Compress'
      line: 'Compress=yes'
      insertafter: '\[Journal\]'
  when:
      - ubtu22cis_rule_4_2_1_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_4.2.1.3
      - rsyslog
      - journald

- name: "4.2.1.4 | PATCH | Ensure journald is configured to write logfiles to persistent disk"
  lineinfile:
      path: /etc/systemd/journald.conf
      regexp: '^Storage|^#Storage'
      line: 'Storage=persistent'
      insertafter: '\[Journal\]'
  when:
      - ubtu22cis_rule_4_2_1_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_4.2.1.4
      - rsyslog
      - journald

# Need 4.2.1.5 Ensure journald is not configured to send logs to rsyslog

# Need 4.2.1.6 Ensure journald log rotation is configured per site policy

# Need 4.2.1.7 Ensure journald default file permissions configured